# Data Manipulation



To start, we import the PyTorch library  
Note that the package name is `torch`

In [1]:
import torch

A tensor represents a (possibly multi-dimensional) array of numerical values

With one axis, a tensor corresponds (in math) to a *vector*  
With two axes, a tensor corresponds to a *matrix*

In [2]:
x = torch.arange(24, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

In [3]:
x.numel()

24

We can access a tensor's *shape*

In [29]:
x.shape # equivalent to x.size()

torch.Size([4])

Change the shape of a tensor without altering its size or values

In [6]:
X = x.reshape(3, 8)
X

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13., 14., 15.],
        [16., 17., 18., 19., 20., 21., 22., 23.]])

Reshaping, in general, doesn't copy the data but output a different view of the tensor

In [7]:
x.data_ptr() == X.data_ptr() # both tensor have the same underlying memory

True

Pytorch can deduce the size of one dimension.

In [8]:
X = x.reshape(-1, 2, 4)
X

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.]],

        [[ 8.,  9., 10., 11.],
         [12., 13., 14., 15.]],

        [[16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

We can construct a tensor with all elements set to zero or one

In [9]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

Sample each element randomly (and independently)

In [11]:
torch.randn(3, 4)

tensor([[ 2.1450, -0.4700,  0.7781, -1.9976],
        [-1.1297, -0.0835,  0.2957,  0.6037],
        [ 0.5461, -0.0817, -0.6347,  1.0844]])

Supplying the exact values for each element

In [12]:
Y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
Y

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

`[-1]` selects the last row and `[1:3]`
selects the second and third rows

In [13]:
Y[-1], Y[1:3]

(tensor([4, 3, 2, 1]),
 tensor([[1, 2, 3, 4],
         [4, 3, 2, 1]]))

We can also write elements of a matrix by specifying indices

In [14]:
Y[1, 2] = 17
Y

tensor([[ 2,  1,  4,  3],
        [ 1,  2, 17,  4],
        [ 4,  3,  2,  1]])

To assign multiple elements the same value, we apply the indexing on the left-hand side of the assignment operation

In [15]:
Y[0:2, :] = 12
Y

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 4,  3,  2,  1]])

In [16]:
torch.exp(x)

tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
        4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04,
        1.6275e+05, 4.4241e+05, 1.2026e+06, 3.2690e+06, 8.8861e+06, 2.4155e+07,
        6.5660e+07, 1.7848e+08, 4.8517e+08, 1.3188e+09, 3.5849e+09, 9.7448e+09])

In [17]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

*concatenate* multiple tensors together

In [18]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

Construct a binary tensor via *logical statements*

In [19]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

Summing all the elements in the tensor

In [20]:
X.sum()

tensor(66.)

Or summing column-wise

In [21]:
X.sum(dim=1)

tensor([ 6., 22., 38.])

Perform elementwise binary operations
by invoking the *broadcasting mechanism*

In [22]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

The common standard arithmetic operators
(`+`, `-`, `*`, `/`, and `**`)
have all been *lifted* to elementwise operations
for any identically-shaped tensors of arbitrary shape.

In [23]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

Running operations can cause new memory to be
allocated to host results

In [24]:
before = id(Y)
Y = Y + X
id(Y) == before

False

Performing in-place operations. Can be dangerous!

In [25]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 4562146864
id(Z): 4562146864


If the value of `X` is not reused in subsequent computations,
we can also use `X[:] = X + Y` or `X += Y`
to reduce the memory overhead of the operation

Use this carefully, can go wrong once we introduce gradient computation

In [26]:
before = id(X)
X += Y
id(X) == before

True

Converting to a NumPy tensor (`ndarray`)

In [27]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

Convert a size-1 tensor to a Python scalar

In [28]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)